# Generated by Django 6.0.1 on 2026-01-26 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=200)),
                ('ProductNumber', models.CharField(max_length=100, unique=True)),
                ('ProductDate', models.DateField()),
                ('DepartmentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.department')),
            ],
        ),
    ]
